services:
  frontend:
    build: 
      context: ..
      dockerfile: Docker/Dockerfile.frontend
    volumes:
      - ../meshapp/frontend:/app
      - /app/node_modules
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - app-network

  backend:
    build: 
      context: ..
      dockerfile: Docker/Dockerfile.backend
    volumes:
      - ../meshapp/backend:/app
    ports:
      - 5000:5000
    environment:
      - FLASK_ENV=development
    networks:
      - app-network

networks:
  app-network:
    driver: bridge