services:
  frontend:
    build: 
      context: ..
      dockerfile: Docker/Dockerfile.frontend
    hostname: frontend
    container_name: frontend
    volumes:
      - ../meshapp/frontend:/app
      - /app/node_modules
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      app-network:
        ipv4_address: 172.16.238.10

  backend:
    build: 
      context: ..
      dockerfile: Docker/Dockerfile.backend
    container_name: backend
    hostname: backend
    volumes:
      - ../meshapp/backend:/app
    ports:
      - 5000:5000
    environment:
      - FLASK_ENV=development
    networks:
      app-network:
        ipv4_address: 172.16.238.11
    runtime: nvidia

networks:
  app-network:
    name: app-network
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24